# Generated by Django 5.2.5 on 2026-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed: original_price * (1 - discount/100), rounded to 2 decimals', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flash_discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flash_discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Flash discount percentage (5-30)'),
        ),
        migrations.AddField(
            model_name='item',
            name='flash_discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_flash_discount_active',
            field=models.BooleanField(default=False, help_text='Whether this product currently has an active flash discount'),
        ),
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price before any flash discount', max_digits=10, null=True),
        ),
    ]
