# Generated by Django 5.2.5 on 2026-05-17 15:35

from django.db import migrations


def backfill_original_price(apps, schema_editor):
    """
    Backfill original_price for all existing items that don't have it set.
    Uses the current 'price' field value as the original_price.
    """
    Item = apps.get_model('item', 'item')
    updated = 0
    for obj in Item.objects.all():
        if obj.original_price is None:
            obj.original_price = obj.price
            obj.save(update_fields=['original_price'])
            updated += 1
    if updated:
        print(f"  Backfilled original_price for {updated} items.")


def reverse_backfill(apps, schema_editor):
    """No-op reverse — we don't clear original_price on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_flash_discount'),
    ]

    operations = [
        migrations.RunPython(backfill_original_price, reverse_backfill),
    ]
