# Generated by Django 5.2.5 on 2026-05-19 12:00

from django.db import migrations


def backfill_item_images(apps, schema_editor):
    """
    For every existing item that has an image, create a corresponding
    ItemImage row so that existing data works with the new multi-image system.
    """
    Item = apps.get_model('item', 'item')
    ItemImage = apps.get_model('item', 'ItemImage')

    items_with_images = Item.objects.exclude(image='').exclude(image=None)
    for item_obj in items_with_images:
        ItemImage.objects.create(
            item=item_obj,
            image=item_obj.image,
            order=0,
        )


def reverse_backfill(apps, schema_editor):
    """Remove all ItemImage rows created by this migration."""
    ItemImage = apps.get_model('item', 'ItemImage')
    ItemImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_add_item_image'),
    ]

    operations = [
        migrations.RunPython(backfill_item_images, reverse_backfill),
    ]
