# Generated by Django 5.2.5 on 2026-05-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_backfill_item_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
