services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"  # <--- THIS LINE IS REQUIRED for pgAdmin to work!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    volumes:
      - .:/app
      - theme_node_modules:/app/theme/static_src/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command:
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
  
  tailwind:
    build: .
    volumes:
      - .:/app
      - theme_node_modules:/app/theme/static_src/node_modules
    command: >
      sh -c "cd theme/static_src && 
             ./node_modules/.bin/postcss ./src/styles.css -o ../static/css/dist/styles.css --watch --poll 1000"

volumes:
  postgres_data:
  theme_node_modules: